//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priem
    {
        public int ID { get; set; }
        public Nullable<int> ID_client { get; set; }
        public Nullable<int> ID_specialist { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
